### ISSUE TITLE
Update Node.js version to 20

### ISSUE THREAD

**Issue by alfonsograziano** [nearform-actions/github-action-check-linked-issues#478]
Every time this action runs we get this warning: 

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: nearform-actions/github-action-check-linked-issues@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

We should consider updating the action platform to Node.js 20

**Comment by simoneb** [comment]
In scope of this, let's also check all other JS actions in that org to see if any other needs updating.
