### ISSUE TITLE
Incompatible Execution Context

### ISSUE THREAD

**Issue by tornupnegatives** [nearform-actions/github-action-check-linked-issues#490]
About a week ago, the action has begun to fail consistently. The error message suggests it is trying to use an execution context that my runner does not support. My runner is the latest version, self-hosted x86 (Linux).

```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
```

My action configuration is below.

```yml
name: Enforce PR-Issue Link Policy
on: [pull_request]

jobs:
  enforce-pr-issue-link-policy:
    runs-on: [self-hosted, linux]
    container: ubuntu:latest
    permissions:
        issues: read
        pull-requests: write
    steps:
      - uses: nearform-actions/github-action-check-linked-issues@v1
        id: check-linked-issues
        with:
          exclude-branches: "release/**, dependabot/**"
          comment: false
```

Any suggestions?

**Comment by simoneb** [comment]
In the [last release](https://github.com/nearform-actions/github-action-check-linked-issues/releases/tag/v1.5.0) we upgraded the action to run on Node 20. In hindsights, we could have bumped a major version.

You can either stay on the previous version or bump your runner as described [here](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).
