### ISSUE TITLE
`loose-matching` is suddenly required since version 1.6.0 (not documented in README)

### ISSUE THREAD

**Issue by jonBerg24** [nearform-actions/github-action-check-linked-issues#505]

**Comment by assafBarash** [comment]
this is not compatible with previous releases and breaks all our PR checks
would appreciate if we can in the meanwhile refer `v1` tag back to `v1.5.0` 🙏

**Comment by simoneb** [comment]
We're looking into it as we speak. Bear with us for a few hours, we'll come up with a solution soon

**Comment by simoneb** [comment]
Solved in #506
